---
- name: Starting Initializing PHP Website
  hosts: EC2
  gather_facts: true
  become: yes

  tasks:
    - name: Updating System Package Links
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Installing Packages
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: latest
      loop:
        - apache2
        - mysql-server
        - php
        - libapache2-mod-php
        - php-mysql
        - unzip
        - python3-pip

    - pip:
        name: pexpect
        state: present

    - shell: |
        chmod 777 /etc/apache2/mods-enabled/dir.conf
      become: yes

    - name: Replace default serving file with rootFile
      shell: |
        sed -i 's/index.html/{{root_file}}/g' /etc/apache2/mods-enabled/dir.conf
      become: yes

    - name: Create Path to Download Zip
      file:
        path: /home/download
        state: directory

    - name: Download Project to directory
      copy:
        src: "{{ zipped_file_path }}"
        dest: /home/download/
        mode: 0777
      register: path_name

    - name: Unarchive Zip and move to /var/www/html
      unarchive:
        src: "{{ path_name.dest }}"
        dest: /var/www/html
        remote_src: yes

    - name: Find SqlDump file
      find:
        paths: /var/www/html
        patterns: "*.sql"
      register: sqldump

    - set_fact:
        sqldump_path: "{{ sqldump['files'][0]['path'] }}"

    - name: Change MySQL Password
      expect:
        command: mysql -u root -p 
        responses:
          Enter password: "" 
          mysql>: "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';exit;"
      ignore_errors: true

    - name: Create Database
      expect:
        command: mysql -u root -p 
        responses:
          Enter password: "root" 
          mysql>: "create database {{ db_name }};exit;"
      ignore_errors: true

    - name: Import Database 
      expect:
        command: mysql -u root -p 
        responses:
          Enter password: "root" 
          mysql>: "use {{ db_name }}; source {{ sqldump_path }};"
      ignore_errors: true
    
    - name: Find all php Files 
      find:
        paths: /var/www/html
        file_type: file
        recurse: yes
        patterns:
          - "*.php"
      register: phpfiles

    - set_fact:
        php_files: "{{ phpfiles['files'] | map(attribute='path') | list }}"

    - set_fact:
        new_db_conn: "mysqli_connect('localhost','root','root','{{db_name}}');"

    - name: Replace all instances of DB Connection
      replace:
        path: "{{ item }}"
        regexp: mysqli_connect\([_',a-zA-Z\s]*\);
        replace: "{{ new_db_conn }}"
      loop: "{{ php_files }}"

    - name: Restart apache2 service
      service:
        name: apache2
        state: restarted
       
    - name: Enable MySQL run on Startup
      service: 
        name: mysql 
        state: started 
        enabled: true
# ---------------------------------------------------------------------------------

    # - name: MySQL | Changing the root password
    #   mysql_user:
    #     user: root
    #     host: "{{item}}"
    #     password: root
    #     login_user: root
    #     login_password: ""
    #     priv: "*.*:ALL,GRANT"
    #   with_items:
    #     - 127.0.0.1
    #     - ::1
    #     - localhost

    # - name: Set New Database
    #   mysql_db:
    #     name: "{{ db_name }}"
    #     state: "present"

    # - name: Importing Data from SqlDump
    #   mysql_db:
    #     name: "{{ db_name }}"
    #     state: import
    #     target: "{{ sqldump_path }}"
