---
- name: Starting Initializing PHP Website
  hosts: EC2
  gather_facts: true
  become: yes

  tasks:
    - name: Updating System Package Links
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Installing Packages
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: latest
      loop:
        - apache2
        - mysql-server
        - php
        - libapache2-mod-php
        - php-mysql
        - unzip

    - shell: |
        chmod 777 /etc/apache2/mods-enabled/dir.conf
      become: yes

    - name: Replace default serving file with rootFile
      shell: |
        sed -i 's/index.html/{{root_file}}/g' /etc/apache2/mods-enabled/dir.conf
      become: yes

    - name: Create Path to Download Zip
      file:
        path: /home/download
        state: directory

    - name: Download Project to directory
      copy:
        src: "{{ zipped_file_path }}"
        dest: /home/download/
        mode: 0777
      register: path_name

    - name: Unarchive Zip and move to /var/www/html
      unarchive:
        src: "{{ path_name.dest }}"
        dest: /var/www/html
        remote_src: yes

    - name: Restart apache2 service
      service:
        name: apache2
        state: restarted

    - name: Enable MySQL run on Startup
      service: name=mysql state=started enabled=true

    - name: Set MySQL Root Password
      mysql_user:
        login_host: "localhost"
        login_user: "root"
        login_password: ""
        name: "root"
        password: "root"
        state: "present"

    - name: Set New Database
      mysql_db:
        name: "{{ db_name }}"
        state: "present"

    - name: Find SqlDump file
      find:
        paths: /var/www/html
        patterns: "*.sql"
      register: sqldump

    - set_fact:
        sqldump_path: "{{ sqldump['files'][0]['path'] }}"
    
    - name: Importing Data from SqlDump
      mysql_db:
        name: "{{ db_name }}"
        state: import
        target: "{{ sqldump_path }}"